### ISSUE TITLE
need better uuid support

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-easybake#35]
The uuid() function currently gives you new, random UUIDv4 results every time it's called. This makes writing tests for it hard (need to mock the calls and supply a known list). Also, uuids aren't very readable in markup meant for humans to read. @philschatz has requested some means of supplying a uuid generator function, and implementing a switch in the cli to use a 'simple id scheme' (probably prefix+incrementing integer) This pass-in-a-generator would be useful for the tests as well, bypassing the need for the mock.

**Comment by philschatz** [comment]
Thanks! As part of "readable HTML" I'd also like to include a `ensure-id: true` CSS declaration whenever a new link is created. but that's an optional nice-to-have

**Comment by philschatz** [comment]
Also, I believe the HTML spec says that id attributes must begin with something other than a number. Just making sure that's what we do 😄

**Comment by philschatz** [comment]
Also, I believe the HTML spec says that id attributes must begin with something other than a number. Just making sure that's what we do 😄 

Also, instead of something like `ensure-id: true`, could easybake just add an `id` attribute to the element whenever `attr(id)` is called?

**Comment by philschatz** [comment]
I just ran into this problem a couple of times today ; (

First time was tangentally-related. In the PDF generation code, whenever a PDF is regenerated all the terms got new id's so it was difficult to search if I fixed the problem.

And tonight I was working on a diff tool for cnx-recipes to make sure refactoring the ruleset code did not affect the resulting HTML.

To get it working locally, I replaced all the references to `uuid4()` with `self.generate_id()` and then added the following code to `oven.py`:

```python
    def generate_id(self):
        """Generate a fresh id"""
        # uuid4()
        self.id_counter += 1
        return 'autobaked-{}'.format(self.id_counter)
```

I also added `self.id_counter = 0` to the `Oven` constructor 😄 


Any pointers on how to get this into the codebase properly?
