### ISSUE TITLE
Counter styles

### ISSUE THREAD

**Issue by reedstrm** [Connexions/cnx-easybake#8]
The content: counter() function needs to take a second optional style argument. This will allow for non-decimal counter styles. See list: https://www.w3.org/TR/CSS2/generate.html#propdef-list-style-type

**Comment by philschatz** [comment]
For what it's worth, here's all the formats (in JS) including `decimal-leading-zero`, `lower-roman`, `upper-roman`, `lower-latin`, `upper-latin`, and `decimal`:
https://github.com/philschatz/css-polyfills.js/blob/master/src/plugins.coffee#L207

Should also work for `target-counter(...)`

**Comment by reedstrm** [comment]
awesome. Thanks @philschatz  that'll help. Hmm, I don't see Azerbaijan in there, though. :-)

**Comment by reedstrm** [comment]
closed by #12
